language: node_js
node_js:
  - "0.10"
script: "npm run $TEST_STEP"
env:
  matrix:
    - TEST_STEP=lint
    - TEST_STEP=test
notifications:
  email: false
services:
  - elasticsearch
before_script:
  - sleep 10
  - patch -p0 < disable-test.patch
before_install:
  - sudo apt-get autoremove --purge elasticsearch
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo service elasticsearch start
  - sleep 30
